name: Hourly Update

on:
  # workflow_dispatch
  schedule:
    - cron: "10 * * * *"

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Configure .env file
        run: |
          touch .env
          echo KEY=${{ secrets.KEY }} >> .env
          echo POS=${{ secrets.POS }} >> .env
          echo PERSTOKEN=${{ secrets.PERSTOKEN }} >> .env
          echo ISGITHUB=${{ secrets.ISGITHUB }} >> .env
          echo SUNKEY=${{ secrets.SUNKEY }} >> .env

      - name: Run hourly update script
        run: |
          npm install
          npm start
