name: Hourly Update

on:
  workflow_dispatch:
  # schedule:
    # - cron: "10 * * * *"

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Run hourly update script
        env:
          KEY: ${{ secrets.KEY }}
          POS: ${{ secrets.POS }}
          PERSTOKEN: ${{ secrets.PERSTOKEN }}
          ISGITHUB: ${{ secrets.ISGITHUB }}
          SUNKEY: ${{ secrets.SUNKEY }}
        run: |
          npm install
          npm start
